# Generated by Django 4.0.3 on 2022-03-06 04:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Titulo')),
                ('conteudo', models.CharField(max_length=500, verbose_name='Conteudo')),
                ('cor', models.CharField(choices=[('primary', 'primary'), ('secondary', 'secondary'), ('success', 'success'), ('info', 'info'), ('warning', 'warning'), ('danger', 'danger')], default='primary', max_length=15)),
                ('datacadastro', models.DateTimeField(auto_now_add=True, verbose_name='Criado em:')),
                ('datamodificacao', models.DateTimeField(auto_now=True, verbose_name='Modificado em:')),
                ('is_done', models.BooleanField(default=False)),
                ('like', models.ManyToManyField(blank=True, related_name='users', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Todo',
                'verbose_name_plural': 'Todos',
            },
        ),
    ]
